name: Tourism Project Pipeline

on:
  push:
    branches: [ main ]

env:
  HF_DATASET_REPO: "labhara/tourism-wellness-dataset"  # <-- set this to your HF dataset repo id

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mask HF token in logs (safety)
        run: echo "::add-mask::${{ secrets.HF_TOKEN }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload dataset to Hugging Face Hub
        run: |
          python tourism_project/src/register_dataset.py \
            --dataset-repo "${{ env.HF_DATASET_REPO }}" \
            --local-path "tourism_project/data/tourism.csv" \
            --path-in-repo "data/tourism.csv" \
            --private \
            --hf-token "${{ secrets.HF_TOKEN }}"

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mask HF token in logs (safety)
        run: echo "::add-mask::${{ secrets.HF_TOKEN }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data preparation
        run: |
          python tourism_project/src/data_prep.py \
            --dataset-repo "${{ env.HF_DATASET_REPO }}" \
            --dataset-path-in-repo "data/tourism.csv" \
            --artifacts-dir "artifacts" \
            --hf-token "${{ secrets.HF_TOKEN }}"

      - name: Upload prepped artifacts for next jobs
        uses: actions/upload-artifact@v4
        with:
          name: data-artifacts
          path: |
            artifacts/data
            artifacts/preprocess
