name: Tourism Project Pipeline

on:
  push:
    branches: [ main ]

env:
  HF_DATASET_REPO: "labhara/tourism-wellness-dataset"  
  HF_SPACE_ID:     "labhara/tourism-wellness-app"      

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mask HF token in logs (safety)
        run: echo "::add-mask::${{ secrets.HF_TOKEN }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload dataset to Hugging Face Hub
        run: |
          python tourism_project/src/register_dataset.py \
            --dataset-repo "${{ env.HF_DATASET_REPO }}" \
            --local-path "tourism_project/data/tourism.csv" \
            --path-in-repo "data/tourism.csv" \
            --private \
            --hf-token "${{ secrets.HF_TOKEN }}"

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mask HF token in logs (safety)
        run: echo "::add-mask::${{ secrets.HF_TOKEN }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data preparation
        run: |
          python tourism_project/src/data_prep.py \
            --dataset-repo "${{ env.HF_DATASET_REPO }}" \
            --dataset-path-in-repo "data/tourism.csv" \
            --artifacts-dir "artifacts" \
            --hf-token "${{ secrets.HF_TOKEN }}"

      - name: Upload prepped artifacts for next jobs
        uses: actions/upload-artifact@v4
        with:
          name: data-artifacts
          path: |
            artifacts/data
            artifacts/preprocess

  model-traning:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: data-artifacts
          path: artifacts

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model (MLflow local tracking)
        run: |
          python tourism_project/src/train.py \
            --artifacts-dir "artifacts" \
            --model-out-dir "artifacts/model" \
            --mlflow-uri "file:./mlruns" \
            --run-name "baseline"

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            artifacts/model
            mlruns

  deploy-hosting:
    needs: [model-traning, data-prep, register-dataset]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: data-artifacts
          path: artifacts
      - uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: artifacts_bundle

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (just what we need to push)
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub -q

      - name: Build Space bundle
        run: |
          rm -rf space-bundle
          mkdir -p space-bundle/artifacts/model
          mkdir -p space-bundle/artifacts/preprocess
          # app & deps
          cp app.py space-bundle/
          cp requirements.txt space-bundle/
          # artifacts: preprocessor/meta from data-prep
          cp artifacts/preprocess/preprocessor.joblib space-bundle/artifacts/preprocess/
          cp artifacts/preprocess/meta.joblib         space-bundle/artifacts/preprocess/
          # artifacts: trained model + copy of meta/preproc from train step
          cp -r artifacts_bundle/artifacts/model/*    space-bundle/artifacts/model/

      - name: Push to Hugging Face Space
        run: |
          python tourism_project/src/push_space.py \
            --space-id "${{ env.HF_SPACE_ID }}" \
            --folder "space-bundle" \
            --hf-token "${{ secrets.HF_TOKEN }}" \
            --sdk streamlit
